### ISSUE TITLE
Uninstaller does not work

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#11]
There is  Cate Core uninstaller in Programs and Features, it’s called: Python 3.5.x (cate 0.8….).
Does not seem to work as after it is run, the cate sub-folders within 

C:\Users\HClifton\AppData\Local\Continuum 
C:\Users\HClifton\AppData\Roaming 

are still populated.

**Comment by forman** [comment]
This is not a *Cate Core* issue, please post it in https://github.com/CCI-Tools/cate-core/issues
