### ISSUE TITLE
SSL “certificate verify failed” error when first using ODP

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#12]
If you have not used ODP before and you try to open a data source from it and are using Windows, there is  SSL “certificate verify failed” error.
Problem only occurs with Windows.

![capture](https://user-images.githubusercontent.com/29569434/27329891-45356780-55af-11e7-8346-4dd451ad0781.PNG)

As a note, the workaround is to open
https://esgf-index1.ceda.ac.uk/projects/esgf-ceda/ in Internet Explorer. After that problem disappears.

**Comment by forman** [comment]
Yepp, I remember this ... then forgot about it. I currently have no idea, how to solve that.

**Comment by forman** [comment]
Closed, because we have it here already: https://github.com/CCI-Tools/cate-core/issues/64
