### ISSUE TITLE
Dataset is shown in list of local datasets before it has finished loading

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#13]
When copying a dataset to local. The dataset is shown in the list of local datasets before it has finished loading.

![capture](https://user-images.githubusercontent.com/29569434/27330049-d031abfa-55af-11e7-9c5e-ff416e467d1a.PNG)

Note: There is a related issue CCI-Tools/cate-core#193 - CLI make_local creates local data source even if the command fails

**Comment by forman** [comment]
Right, that's no good. The good thing is, that this will prevent from creating another local data source with the same name.

I suggest, we indicate the new data source  as being incomplete and while it is downloading, we disable the *open* button.

**Comment by HelenClifton** [comment]
Confirmed fixed in 0.9.0-dev4.
