### ISSUE TITLE
"Save Workspace As" does not work

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#14]
When File->Save Workspace As is selected, there isn't a way to enter the name for the new workspace. 
![capture](https://user-images.githubusercontent.com/29569434/27330397-21291e3e-55b1-11e7-9ace-205d76c72451.PNG)

If "Select" is clicked, an error message is shown

![capture](https://user-images.githubusercontent.com/29569434/27330433-468b67fe-55b1-11e7-9700-10cc0d5a39dd.PNG)

**Comment by forman** [comment]
Yes, a known problem. To get around it: create an empty directory first and then select its name. 

We actually need a directory chooser.

**Comment by forman** [comment]
This issue was moved to CCI-Tools/cate-core#419
