### ISSUE TITLE
Image artefacts on 3D Globe view

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#15]
Visual artefacts are seen on 3D Globe view at both poles (before any data is displayed) 
Locations of artefacts change as you zoom in and out. 

![capture](https://user-images.githubusercontent.com/29569434/27330573-e13dcb02-55b1-11e7-964c-c3e31d7f12da.PNG)

![capture](https://user-images.githubusercontent.com/29569434/27330602-febeede6-55b1-11e7-91d2-11061e6c5a3e.PNG)

**Comment by forman** [comment]
Have you manipulated layer settings before? This artifacts are known to occur if you increase the image's *gamma* value.

**Comment by HelenClifton** [comment]
I did not change any of the layer settings.
The issue can be reproduced as follows:
1. Open cate desktop
2. Flip Globe view so that South pole is visible
3. Using left mouse button, zoom out in one step at a time
4. Using left mouse button, zoom in, one step at a time
5. Flip Globe view so that North pole is visible
6. Using left mouse button, zoom out in one step at a time
7. Using left mouse button, zoom in, one step at a time

**Comment by forman** [comment]
This issue was moved to CCI-Tools/cate-core#418
