### ISSUE TITLE
Unsuitable word in messages to user

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#17]
Several messages to the user, including when the Desktop is opened, contain the word "back-end"

Unfortunately, this word has another meaning in English which could cause offence to some users.

Please replace the term "back-end" with something else.

**Comment by forman** [comment]
I'm surprised. To us computer people this is such a common wording. I also wasn't able to understand what the "offense" in this case may be.

* https://en.wiktionary.org/wiki/back_end#English
* https://en.wikipedia.org/wiki/Front_and_back_ends
* http://dict.leo.org/englisch-deutsch/back-end

**Comment by HelenClifton** [comment]
The word "back end" is sometimes used by native English speakers as slang for a part of the human body. 
This usage is not always in dictionaries !
The use of the word "back end" in the error messages may well cause amusement to some users, because of this other meaning. However, not everyone will find it funny, so it is best to replace it with something else.
I hope this helps !

**Comment by forman** [comment]
Could you then please provide some alternative wordings that have the same meaning as "back end".

**Comment by HelenClifton** [comment]
Suggest "cate core" or "cate service"
