### ISSUE TITLE
Cate is loading two separate datasets into the same resource

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#18]
**Expected behavior**

Opened a remote data source with no constraints. Starts loading it into dataset_res1.
While it is still being opened, opened a local data source with no constraints. Expect that a new resource res2 is created.

**Actual behavior**
Instead, cate is attempting to load both datasets into the same resource res1.

![capture](https://user-images.githubusercontent.com/29569434/27373310-bb6720aa-565f-11e7-8c73-60b79afacc30.PNG)

**Steps to reproduce the problem**

1. Select esacci.AEROSOL... remote data source as seen above. 
2. Click open data source, no constraints. 
3. While it is loading, change data store in drop down list to local
4. Select a local data source . Click open data source, no constraints

**Specifications** 
cate 0.8.0-rc5
Internet Explorer 11
Windows 7 Professional

**Comment by forman** [comment]
We need a new concept of how to name resources according to their originating datasets and their producing operations. 

1. Users should be able to provide a name on their own (open data source dialog, apply operation dialog)
2. The software could make suggestions following a pattern such as 
   * <ds_name>_<time>_<area> for resources from opening datasets
   * <source_res_name>_<operation_name> for resources from operations

**Comment by forman** [comment]
See also #7

**Comment by HelenClifton** [comment]
Confirmed fixed in 0.9.0-dev4
It now creates a second resource

**Comment by forman** [comment]
Fixed by https://github.com/CCI-Tools/cate-core/issues/391
