### ISSUE TITLE
colour bar and scroll time-axis

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate-desktop#39]
Originally opened by @HerzogStephan in cate-core.

### Expected behaviour

One should be able to change and limit the colour bar. In addition, being able to 'scroll' through the time-axis and see the data evolve in time (on the displayed globe) would be nice.

### Actual behaviour

Either the functionality is not yet implemented or I do not find it (i.e. that part might not be intuitive though).

### Specifications 

Cate 0.9.0.dev4

### Comment

I hope this is not cross-posting - as I did not found a comparable issue.

**Comment by forman** [comment]
Should not be here
