### ISSUE TITLE
'2D Map' does not scale properly when activiated via 'View'-panel

### ISSUE THREAD

**Issue by MartinMonkos** [CCI-Tools/cate-desktop#42]
### Actual behavior

When switching to 2D world view via the 'view'-panel and adjusting any other frame in width, the map does not scale properly. It gets deformed (squeezed).
(Though 2D world view works fine, when activated via the drop down button inside the map frame in the upper right corner.)

### Expected behavior

When resizing any frame in width, the frame should roll over the map without deforming it, or scale it proportionately .

### Steps to reproduce the problem

1. Click on 'View'-Panel
2. Select '2D Map'
3. Change any frame's width.

### Specifications 

Linux, 0.9.0-dev5

**Comment by forman** [comment]
As decided at IRM6, we'll drop supporting the 2D map
