### ISSUE TITLE
Location of window when re-opening cate-desktop

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#6]
**Actual behavior**
When you close Cate and re-open it, the window doesn't appear in the same location in the Windows desktop as it was before

**Expected behaviour**
It should re-open in same place

**Specification**
cate-desktop 0.8.0-rc5

**Comment by forman** [comment]
Already fixed in 0.8.0-rc6

**Comment by HelenClifton** [comment]
Was fixed in 0.8.0-rc6.
