### ISSUE TITLE
Naming of open resources

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#7]
**Actual behavior**
In the Workspace, the Resource name bears no relation to the dataset  which has been opened. It is given a default name like "res_1_Dataset". If several data sources are opened it is not easy to tell which is which. (But you can rename after it has opened)

**Expected behaviour**
 Allow user to set the resource name when they open the dataset.

**Specification**
 cate-desktop 0.8.0-rc5

**Comment by forman** [comment]
I fully agree.

**Comment by forman** [comment]
Fixed by https://github.com/CCI-Tools/cate-core/issues/391
