### ISSUE TITLE
Cannot see all the text in Value column

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#8]
**Actual behavior**
In Workspace, under Details, if the text in the Value column is longer than the width of the column, it cannot be displayed.
![capture](https://user-images.githubusercontent.com/29569434/27329196-ac1bd162-55ac-11e7-91cb-8779b538d930.PNG)

**Expected behaviour**
 Allow user  to scroll horizontally to read all the text

**Specification**
 cate-desktop 0.8.0-rc5

**Comment by forman** [comment]
But you should be able to make a column wider, no?

**Comment by HelenClifton** [comment]
Ah, I had not realised it was possible to make the column wider.
Yes, if I make the column wider, I can see all of the text.
I think that adding a scroll bar would still be a useful enhancement, but I agree this issue is not a bug.

**Comment by forman** [comment]
In 0.8.0-rc.7.dev.2, you can now click a `...` button in a cell that will display the full value in a pop-up label.

**Comment by HelenClifton** [comment]
Confirmed fixed in 0.9.0-dev4
