### ISSUE TITLE
Unhelpful message to user when remote data source cannot be opened

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate-desktop#9]
Actual behaviour
If a remote data source cannot be opened, the error pop-up which appears does not tell the user what the problem is

![capture](https://user-images.githubusercontent.com/29569434/27329405-5b208a22-55ad-11e7-907c-e9f1273ab8e6.PNG)

Expected behaviour
Pop-up should say something like "Cannot open remote data source" and maybe give suggestions for things to check, e.g. is there an internet connection

Specification
 cate-desktop 0.8.0-rc5

**Comment by forman** [comment]
This issue was moved to CCI-Tools/cate-core#421
